defaults:
  - model     : c-dsvae
  - datamodule: sprite_JunwenBi

logger:
  save_dir         : "logs/"
  name             : "cdsvae_sprite"
  default_hp_metric: False

experiment:
  # manual_seed: 1265
  manual_seed:

trainer:
  gpus                : [0]
  max_epochs          : 500
  enable_progress_bar : True
  deterministic       : False
  log_every_n_steps   : 1

optimizer:
  lr   : 0.001
  betas: [0.9, 0.999]

scheduler:
  name: "none"

checkpoint:
  every_n_epochs          : 50
  save_top_k              : -1
  save_last               : True
  monitor                 : "loss"

reload:
  path:

memo: ""