defaults:
  - model     : c-dsvae_dclaw
  - datamodule: action_norm_valve

logger:
  save_dir         : "./logs/"
  name             : "cdsvae_dclaw"
  default_hp_metric: False

experiment:
  # manual_seed: 1265
  manual_seed:

trainer:
  gpus                : [0]
  max_epochs          : 300
  enable_progress_bar : True
  deterministic       : False
  log_every_n_steps   : 1

optimizer:
  lr   : 0.001
  betas: [0.9, 0.999]

scheduler:
  name: "none"

loss:
  contrastive_loss:
    tau      : 0.5
    normalize: True
  mutual_information:
    # name : "JunwenBai"
    name : "mylogdensity"
  weight:
    kld_context          : 1
    kld_dynamics         : 1
    contrastive_loss_fx  : 10.0
    contrastive_loss_zx  : 10.0
    mutual_information_fz: 10.0

checkpoint:
  every_n_epochs          : 50
  save_top_k              : -1
  save_last               : True
  # save_on_train_epoch_end : True
  # monitor                 : "loss"

reload:
  path:

memo: ""